import type { Metadata } from "next";
import "./globals.css";
import {  merriweather } from "@/components/ui/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.className} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
